### ISSUE TITLE
Vincular as permissões aos grupos do AD

### ISSUE THREAD

**Issue by fabriciorissetto** [CWISoftware/InfraMap#10]
Verificar todos os grupos do usuário ao ele logar. Assim conseguimos vincular as permissões a esses grupos. 
Ou seja, só daremos permissão de "Gerente" ao usuário se ele estivendo dentro do grupo de "Gerentes/Gestores CWI". O mesmo vale para a infra.

**Comment by franklinamormino** [comment]
Pendente nome dos grupos.
