### ISSUE TITLE
Adição/Edição de maquina

### ISSUE THREAD

**Issue by BrunoVerch** [CWISoftware/InfraMap#39]
Não dá mensagem de erro quando repete uma máquina de patrimônio ou TAG iguais.... seja na inserção ou edição / troca de lugar.
Adicionar a pesquisa pelo patrimônio da máquina

**Comment by franklinamormino** [comment]
Estou fechando o bug como inválido, pois na verdade a issue de pesquisa pelo patrimônio ainda não foi implementada, o que ao meu ver é necessário para verificação das máquinas.
A troca de máquina de lugar também não foi implementada.
Já existem duas issues cadastradas para as features serem implementadas, #23 e #24 .
